eslint:
  enabled: true
  config_file: .eslintrc
  ignore:
    - '__dirname is not defined'
    - 'require is not defined'
    - "Parsing error: 'import' and 'export' may appear only with 'sourceType: module'"
  global:
    - require
    - __dirname
  rules:
    no-undef:
      - 2
      - { 'typeof': true }
      