version: '3'

services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '5432:5432'

volumes:
  postgres-db:
    driver: local