version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run coveralls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
