version: 2.1

workflows:
  Test_and_Coverage:
    jobs:
      - Test_and_Send_Coverage

jobs:
  Test_and_Send_Coverage: 
    executor: node/default 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm ci
          name: Install Packages
      - run:
          name: Run Tests
          command: npm test
