version: 2.1

workflows:
  Test_and_Covarage:
    jobs:
      - Test_and_Send_Coverage

jobs:
  Test_and_Send_Coverage:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
