version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - run:
          name: Send coverage report to Coveralls
          command: nyc report --reporter=text-lcov | coveralls
          when: always
          environment:
            COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN

      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - build_and_test
